default:
  tags:
    - pitshop


# NOTE: this likely only works with the shell executor and only if all jobs are queued on the same runner, since it assumes the environment is kept between stages
stages:
  - install
  - lint
  - test


# stage: install
install:
  stage: install
  script:
    - pip3 install pipenv wheel
    - export PATH="~/.local/bin:$PATH"
    - pipenv sync --dev -v
    - pipenv clean -v


# stage: lint
format:
  stage: lint
  script:
    - pipenv run pre-commit run --show-diff-on-failure --color=always --all-files

# mypy:
#   stage: lint
#   script:
#     - pipenv run mypy .


# stage: test
# TODO: use postgres instead of sqlite
pytest:
  stage: test
  script:
    - pipenv run python manage.py flush --noinput
    - pipenv run coverage erase
    - pipenv run pytest .
  coverage: '/TOTAL.* (\d+.\d+)%$/'
  artifacts:
    reports:
      cobertura: coverage.xml
