# Generated by Django 4.0.2 on 2022-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subordermaterial',
            name='size_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subordermaterial',
            name='size_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
